# Generated by Django 3.2 on 2024-03-10 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organiztion', '0002_auto_20240310_0639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('image', models.ImageField(null=True, upload_to='events/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('organizations', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organiztion.organization')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ['-date'],
            },
        ),
    ]
