# Generated by Django 3.2 on 2024-03-10 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organiztion', '0002_auto_20240310_0639'),
        ('events', '0002_auto_20240310_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='organizations',
        ),
        migrations.AddField(
            model_name='event',
            name='organizations',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='organiztion.organization'),
            preserve_default=False,
        ),
    ]
