# Generated by Django 3.2 on 2024-03-10 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organiztion', '0002_auto_20240310_0639'),
        ('events', '0003_auto_20240310_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organiztion.organization'),
        ),
    ]
