# Generated by Django 3.2 on 2024-03-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organiztion', '0002_auto_20240310_0639'),
        ('events', '0004_alter_event_organizations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='organizations',
        ),
        migrations.AddField(
            model_name='event',
            name='organizations',
            field=models.ManyToManyField(to='organiztion.Organization'),
        ),
    ]
