# Generated by Django 3.2 on 2024-03-11 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organiztion', '0002_auto_20240310_0639'),
        ('user', '0005_alter_user_organizations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organizations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organiztion.organization'),
        ),
    ]
